epoch: 200

LearningRate:
  base_lr: 0.000125
  schedulers:
    - !CosineDecay
      max_epochs: 360
    - !LinearWarmup
      start_factor: 0.
      epochs: 5

OptimizerBuilder:
  clip_grad_by_norm: 35.0
  optimizer:
    type: AdamW
    weight_decay: 0.05
